name: CI

on:
  release:
   types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          # The name of the image you would like to push
          name: meauris/syslogoms
          # The login username for the registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # The login password for the registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          # Use tag_names when you want to push tags/release by their git name
          # tag_names: # optional
